#!/bin/bash
################################################################################
# 
# Rain
#
# Rain wraps the creation of the NIDIS U.S. drought protal up. It requires the
# the GIT_EMAIL and GIT_NAME are set. 
#
################################################################################


################################################################################
#
# router [parameter] 
#
################################################################################

function router {

  local inputs = $@

  echo $@
  
}

# Call the router with all the parameters.
router
