#!/bin/bash
################################################################################
# Script to start/stop Apache Tomcat
#
# Author: Jon Burroughs
# 
# Run "tomcatd help" to print usage
################################################################################

# Default timeout setting, can override with [-t SECONDS]
TIMEOUT=15

function usage() {
cat <<EOF
Basic Usage: 
tomcatd {start|stop|restart|status|digest|help}

Advanced Flags:
[-h CATALINA_HOME]  Overrides CATALINA_HOME
[-b CATALINA_BASE] [-t NN ] {start|stop|restart|status}
    -b  Overrides CATALINA_BASE
    -t  Specifes time to wait on Tomcat shutdown before issuing a kill to the Tomcat process 
EOF
}

# Startup tomcat
function tomcat_start() {
   if [ -f $CATALINA_HOME/bin/startup.sh ]
   then
      echo $"Starting Tomcat"
      $CATALINA_HOME/bin/startup.sh
      PID=`cat $CATALINA_PID`
      echo "CATALINA_PID: $PID"
   else 
      echo "Could not find CATALINA_HOME/bin/startup.sh.  Is CATALINA_HOME set?"
      exit 1
   fi
}

# Attempts to shutdown tomcat syncronously
function tomcat_stop() {
   if [ -f $CATALINA_HOME/bin/shutdown.sh ]
   then
      echo $"Stopping Tomcat"
      $CATALINA_HOME/bin/shutdown.sh
   else 
      echo "Could not find CATALINA_HOME/bin/shutdown.sh.  Is CATALINA_HOME set?"
      exit 1
   fi

   if [ -f $CATALINA_PID ]
   then
      PID=`cat $CATALINA_PID`
      while ps --pid $PID > /dev/null  && [ $TIMEOUT -ge 0 ] 
      do
         echo "Waiting for tomcat to shutdown... $TIMEOUT"
         sleep 1
         let TIMEOUT-=1
      done

      if ps --pid $PID > /dev/null
      then
         echo 'Timeout exceeded, killing Tomcat...'
         kill -9 $PID
      else
         echo "Tomcat shutdown"
      fi
   fi
}

function tomcat_digest() {
  if [ -f $CATALINA_HOME/bin/digest.sh ]
  then
    $CATALINA_HOME/bin/digest.sh -a SHA $1|cut -f 2 -d : 
  else
    echo "Could not find CATALINA_HOME/bin/digest.sh.  Is CATALINA_HOME set?"
    exit 1
  fi
}

# Report Tomcat status
function tomcat_status() {
   if [ -f $CATALINA_PID ]
   then
      PID=`cat $CATALINA_PID`
      if ps --pid $PID > /dev/null
      then
         echo "Tomcat is running: PID=$PID"
      else
         echo "Tomcat is not running"
      fi
   else
      echo "Cannot find Tomcat PID file"
   fi
}

# Parse options
while getopts "h:b:t:" opt; do
    case $opt in
        h)
          CATALINA_HOME=$OPTARG
          export CATALINA_HOME
          ;;
       
        b) 
          CATALINA_BASE=$OPTARG
          CATALINA_PID=$CATALINA_BASE/tomcat.pid
          export CATALINA_BASE
          export CATALINA_PID
          ;;
        t)
          TIMEOUT=$OPTARG
          ;;
        \?)
          usage
          ;;
        *)
          ;;
     esac
done

shift $(($OPTIND - 1))

# If CATALINA_BASE is not set in the environment, then set CATALINA_PID 
# to CATALINA_HOME/tomcat.pid
if [ -z "$CATALINA_BASE" ]; then
    export CATALINA_BASE=$CATALINA_HOME
    export CATALINA_PID=$CATALINA_HOME/tomcat.pid
fi

# Command-line args
case "$1" in
  start)
    tomcat_start
    ;;
  stop)
    tomcat_stop
    ;;
  restart)
    tomcat_stop
    sleep 5
    tomcat_start
    ;;
  status)
    tomcat_status
    ;;
  digest)
    tomcat_digest $2
    ;;
  help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac

exit $?
